### ISSUE TITLE
Arrow keys don't work in open/save file dialog

### ISSUE THREAD

**Issue by eriksvedang** [yishn/Sabaki#130]
When I go to the open menu and try to navigate the modal open menu using the arrow keys it seems like the app intercepts these keypresses.

I'm on OSX 10.11.6.

(Great app by the way!)

**Comment by yishn** [comment]
Thank you for reporting! This is likely an Electron issue, I've reported it at electron/electron#7248.

**Comment by yishn** [comment]
The developers at Electron marked it as won't fix. There are some possible ways to solve this within Sabaki:

1. Instead of open/save file sheets (attached to the window), we can use open/save file dialogs (not attached to the window). Doing this would solve this issue.
2. Instead of defining the arrow keys as main menu item shortcuts, we attach events to the DOM and handle the corresponding key presses there.

There are some caveats. For solution 1, dialogs don't look as good as sheets. With solution 2, the user won't get any hints as how to navigate through the game. 

Since solution 1 looks like the lesser evil, I'll go on and implement that.

**Comment by eriksvedang** [comment]
OK, sounds good to me!

**Comment by yishn** [comment]
Solution 1 has another caveat: It creates non-modal dialogs, even though the dialogs are blocking. This is unacceptable.

I'm considering another solution: Before opening open/save file dialogs, we disable all menu items. After closing, restore them to their previous state again.
