### ISSUE TITLE
Build Sabaki-Web as a standalone npm package?

### ISSUE THREAD

**Issue by aleadag** [yishn/Sabaki#135]
I am looking at the possibility of building an Anki add-on using Sabaki-Web. Is it possible to build Sabaki-web as npm package so that it can be reused?

**Comment by yishn** [comment]
I don't think it's appropriate to publish Sabaki web on npm since Sabaki is not built to be used as a library:

* Sabaki is not just a component that can be embedded into any web page. It's a full single page application.
* Due to its nature, Sabaki changes global states. Something we don't want in a library.
* Sabaki doesn't have an official public API yet, let alone documentation. I'm changing/removing/adding functions at will right now.

That said, I'm currently working on a public API for Sabaki, so that one can use JS to interact with Sabaki (desktop and web). But even then, publishing to npm seems kind of pointless. So I'm marking this as won't fix.
