### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by Seth-Rothschild** [yishn/Sabaki#199]
This almost certainly is an issue of my own ignorance/setup. I have not used npm or electron before. Here is the terminal output:

```
Seths-MacBook-Pro-2:Sabaki seth$ npm run pack

> sabaki@0.30.1 pack /Users/seth/Desktop/Repositories/Sabaki
> build --dir

No native production dependencies
Packaging for darwin x64 using electron 1.6.7 to dist/mac
⚠️  App is not signed: cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://github.com/electron-userland/electron-builder/wiki/Code-Signing
```
Any advice or anything I could try to get more information would be helpful.

**Comment by Seth-Rothschild** [comment]
Closing this because I am an idiot. This did not prevent packaging, the build was just stored in a place I was not looking... /Sabaki/dist/mac/

**Comment by apetresc** [comment]
Correct. To help anyone else Google-ing this error and finding this ticket: all it means is that electron-builder wasn't able to sign the `.app` bundle, which means that it can't be uploaded to the Mac App Store (and if you were to e-mail it to a friend, they would have to go into Security.prefs and allow apps from unidentified developers, since Apple can't verify who built the app). But it shouldn't prevent you from running the .app on your own machine :)
