### ISSUE TITLE
"Pause" command is disabled during engine matches

### ISSUE THREAD

**Issue by raspingbard** [yishn/Sabaki#217]
When you run a match between two GTP engines, the new "Pause" command on the Engines menu in Sabaki v0.30.3 is disabled.  Isn’t the purpose for it to be enabled during engine matches?

Also, when starting a match you receive the message “Press esc to stop generating moves.”  I’m wondering if this message should now be changed to “Select Pause to stop generating moves”, or something similar.

**Comment by yishn** [comment]
The 'Pause' command terminates engine processes but leaves them attached in Sabaki (as discussed in #205), not to stop generating moves. Maybe it's better to name it 'Suspend'?

**Comment by raspingbard** [comment]
If 'Pause' terminates engine processes, how does it also not stop generating moves?  I don't understand.

'Suspend' would be an equally good name.

**Comment by yishn** [comment]
It's a limitation of Sabaki. While in 'busy mode' the user can't interact with the current window to prevent you from changing the board while the engine is working, in order to prevent syncing issues. For simplicity, Sabaki disables all menu items while in 'busy mode' (except for menu items that triggers actions in the main process). 

I don't want to make an exception for the 'Pause' command, that's why it's being disabled as well. To stop generating moves gracefully, press <kbd>Esc</kbd>. After the engine stops working, the 'Pause' command is available. I'm marking this as wontfix.

**Comment by yishn** [comment]
Also, I forgot to mention one thing. Sabaki tries to stop generating moves gracefully, meaning waiting for the engine to answer before stopping completely. This is also to avoid syncing issues with the engines. 

It's almost always better to stop generating moves gracefully than to terminate engine processes directly, as restarting the engines requires Sabaki to place existing stones one by one in a non-game order, which removes ko information and may or may not influence engine efficiency.

Therefore, 'Suspend' engines should not be used to stop generating moves.
