### ISSUE TITLE
Sabaki 0.30.3 doesn't display moves from Leela on Windows 10

### ISSUE THREAD

**Issue by bixbyr** [yishn/Sabaki#231]
When I attach Leela 0.10.0 (why does attaching an engine necessitate a new game now? The previous way worked just fine and could be used to explore positions) to Sabaki 0.30.3 I hear sounds for the programs moves but the board does not show them. Opening the GTP console shows that the program has played, and when I play the stones appear, but further moves from Leela don't also don't appear on the board.

Sorry to file a vague bug report, but something seems very badly broken with the latest version of Leela and Sabaki. Self play between two versions of Leela produces no moves on the board, and a very confusing jumble on the GTP console that seems to be changing the colors of the stones every move and only playing all white / all black stones.

**Comment by yishn** [comment]
Leela v0.10.0 works fine here on Windows. To make your bug report less vague, can you tell us what OS you're using and what you see in the GTP console? Remember to use the engine only version of Leela with `--gtp` argument. 

You don't need to start a new game to attach an engine. Just attach the engine in the game info drawer anytime.

**Comment by raspingbard** [comment]
I’m finding a lot of bugs with the new Leela v0.10.0 engine that I didn't have with earlier versions:
1)  Receive GTP connection errors during games.
2)  Engine frequently feezes up during move evaluations.
3)  Uses < 70% of CPU on my Mac.  Leela v0.9.0 uses > 320%.
4)  Suddenly starts playing first line blunder moves during complicated fights.

The new UI interface has a number of troubles too.  I think I'm going to downgrade until Gian-Carlo figures this all out.

**Comment by MultiplyByZer01** [comment]
You must use:

```shell
> Leela0100GTP.exe --gtp
```

To put Leela into GTP mode.

**Comment by yishn** [comment]
I'm closing this as I don't think it's a bug on Sabaki's side.

**Comment by gcp** [comment]
>I think I'm going to downgrade until Gian-Carlo figures this all out.

It would help if people would actually report bugs they find, else you'll be waiting for eternity. This is the first time I hear there's any issues with Sabaki, or that there's any issues with the native GUI (and I still have no idea what they would be!). The only known bug in 0.10 is that the engine is very weak on small boards, so this is the only thing that will be fixed in 0.11.

Leela supports producing a logfile with the --logfile command, which will show the interaction between it and Sabaki. That should allowing figuring out who's at fault here.

**Comment by apetresc** [comment]
@gcp Oh, hello :) For myself, there have been a couple of things I've wanted to report on Leela, but since the Leela webpage doesn't ask feedback or provide an e-mail address, I felt like it would have been intrusive to message you with them (even though I did know your e-mail from computer-go@).

Is that not the case? Should we feel free to message you with questions/reports about Leela?

**Comment by gcp** [comment]
Sure, please email me. My email is on the frontpage of sjeng.org, and the About box in the program has it too.

**Comment by raspingbard** [comment]
GCP, I’m sorry for the delay in responding.  I’ve encountered a number of bugs with Leela v0.10.0 using Sabaki that I didn’t have with v0.9.0.  I also wasn’t sure if I should send these reports directly to your email address as I didn’t want to be intrusive.  I will go ahead and send you a bug report later today.

**Comment by gcp** [comment]
I did some testing on Windows 10 and everything seems to be working normally here. The more detailed reports I got were all people using OpenCL on macOS, which is known to be problematic due to the extremely poor state of macOS video drivers.

There's a bug with how Sabaki handles passes, which I'll file separately.
