### ISSUE TITLE
Theme uninstallation not working w/ disabled recycle bin

### ISSUE THREAD

**Issue by ParmuzinAlexander** [yishn/Sabaki#242]
One and the same theme can be install many times.
Uninstall theme not working (win x64).

**Comment by yishn** [comment]
It's intended that you can install the same theme multiple times, since there is no easy way to check if a theme has already been installed or not. 

Uninstalling themes works fine here. Can you [open the developer tools][1] and see if you can see any errors? To remove themes manually, you can empty the folder `%APPDATA%\Sabaki\themes`.

[1]: https://github.com/yishn/Sabaki/blob/master/docs/guides/debugging.md

**Comment by ParmuzinAlexander** [comment]
I no see errors in console, just this http://imgur.com/s1I0ORE

**Comment by yishn** [comment]
This means that Sabaki couldn't move the theme folder to the trash. Can you try and see if you can manually remove the theme folder? Or do you, by any chance, have the recycle bin disabled? I just found this issue: electron/electron#4974

**Comment by ParmuzinAlexander** [comment]
Now it is clear. Of course recycle bin disabled.

**Comment by yishn** [comment]
I think we should keep this issue open. Sabaki should simply remove the theme folder permanently if recycle bin is disabled.
