### ISSUE TITLE
bug: crash in "autoplay mode"

### ISSUE THREAD

**Issue by NodosDsnn** [yishn/Sabaki#251]
close application, when change seconds with keyboard and press enter.

tested in version 0.31.0 linux-x64.AppImage

**Comment by yishn** [comment]
Thank you for reporting!

**Comment by fohristiwhirl** [comment]
I tried to look at this but couldn't figure it out, perhaps because I don't know React. It seems like a clean exit, for example it will ask to save the file if needed.

**Comment by yishn** [comment]
I think when you press enter, the browser will try to submit the [`<form>`](https://github.com/yishn/Sabaki/blob/master/components/bars/AutoplayBar.js#L83) the `<input>` element is in. But since the `<form>` has no `action` attribute, the browser is sending the data to the current page, effectively reloading the page. And for some reason, Electron doesn't handle page reloading that well (at least with Sabaki). This should be fixed if we handle the `onSubmit` event of the `<form>` in question and just `evt.preventDefault()` on it.

**Comment by NodosDsnn** [comment]
Thank you for Sabaki ! :D
