### ISSUE TITLE
Sabaki allows cycles in games?

### ISSUE THREAD

**Issue by ikirill** [yishn/Sabaki#328]
Not necessarily a bug, depending on what you intended, but could you clarify what ruleset Sabaki uses? I can't find it in the readme, is it just Japanese rules? For example, it seems to use a local ko rule that forbids only immediate repetitions, which I think makes it inconsistent with Chinese and AGA rules, which use some kind of a superko rule (https://senseis.xmp.net/?Superko).

This game (https://gist.github.com/anonymous/8c4482e49a009bd862d2dbccaa25a271) ends in the same position as after move 1, with white to move, so I think under most Go rules it should either forbid the last black move or end the game in "no result".

Also in a send-2-return-1 seki (https://gist.github.com/anonymous/3b53b8f3587d85d046ccbfe9a7111406) Sabaki allows repetition, but I think both Chinese and AGA rules would forbid it.

**Comment by yishn** [comment]
Sabaki is not enforcing any rules beside the obvious ones, so that anyone can play according to their own rules. It merely gives a warning (which can be disabled) when you play a suicide move or when it repeats the previous board arrangement. Superko is expensive since it involves checking all of the previous board positions.
